name: Cypress Tests
run-name: testing actions
on: [push]

jobs:
  Runnning_Tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./main react
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Install NPM dependencies, cache them correctly
        # and run all Cypress tests
        with:
          cache-dependency-path: './main react/package-lock.json'
      - name: list files
        run: ls -la
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
